intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{reflect-cpp}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{reflect-cpp}: {hxx ixx txx cxx c h}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cc.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

obja{*}: cxx.poptions += -DREFLECT_CPP_STATIC_BUILD
objs{*}: cxx.poptions += -DREFLECT_CPP_SHARED_BUILD

# Export options.
#
lib{reflect-cpp}:
{
  cc.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cc.export.libs = $intf_libs
}

liba{reflect-cpp}: cxx.export.poptions += -DREFLECT_CPP_STATIC
libs{reflect-cpp}: cxx.export.poptions += -DREFLECT_CPP_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{reflect-cpp}: bin.lib.version = "-$version.project_id"
else
  lib{reflect-cpp}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
